export const SalesStage = {
    RENTAL_REQUEST_RECEIVED: 'RENTAL_REQUEST_RECEIVED',
    CUSTOMER_CREATED: 'CUSTOMER_CREATED',
    QUOTE_DRAFT: 'QUOTE_DRAFT',
    QUOTE_SENT: 'QUOTE_SENT',
    QUOTE_ACCEPTED: 'QUOTE_ACCEPTED',
    PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
    JOB_CREATED: 'JOB_CREATED',
    JOB_SCHEDULED: 'JOB_SCHEDULED',
    JOB_COMPLETED: 'JOB_COMPLETED'
} as const;

export type SalesStage = typeof SalesStage[keyof typeof SalesStage];