export enum SalesStage {
  RENTAL_REQUEST = 'RENTAL_REQUEST',
  CUSTOMER_CREATED = 'CUSTOMER_CREATED',
  QUOTE_DRAFT = 'QUOTE_DRAFT',
  QUOTE_SENT = 'QUOTE_SENT',
  QUOTE_ACCEPTED = 'QUOTE_ACCEPTED',
  JOB_CREATED = 'JOB_CREATED',
  INSTALLATION_SCHEDULED = 'INSTALLATION_SCHEDULED',
  COMPLETED = 'COMPLETED'
}